
project_id = "zcftdyamlgcvnduafxzj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Enable the Blogger auth function
[functions.blogger-auth]
verify_jwt = true
