
project_id = "zcftdyamlgcvnduafxzj"

[api]
# Swagger documentation for the API
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Database configuration for Postgres
port = 5432
major_version = 15

[studio]
port = 3000

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://localhost:3000"

[auth.email]
enabled = true
double_confirm_changes = true
# double_confirm_changes = true
# 📚 https://github.com/supabase/gotrue

[realtime]
enabled = true

[functions]
serve_port = 54323

# Define edge functions
[functions.serpapi]
verify_jwt = true

[functions.shopify-connect]
verify_jwt = true

[functions.shopify-products]
verify_jwt = true

[functions.shopify-seo]
verify_jwt = true

[functions.shopify-optimize]
verify_jwt = true

[functions.shopify-bulk-optimize]
verify_jwt = true
