
project_id = "lovable-project"

[functions.serpapi]
verify_jwt = true

[functions.shopify-connect]
verify_jwt = true

[functions.shopify-products]
verify_jwt = true

[functions.shopify-seo]
verify_jwt = true

[functions.shopify-optimize]
verify_jwt = true

[functions.shopify-bulk-optimize]
verify_jwt = true

[functions.gemini-content]
verify_jwt = true

[functions.gemini-image]
verify_jwt = true
