// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcftdyamlgcvnduafxzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjZnRkeWFtbGdjdm5kdWFmeHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NTE0NDgsImV4cCI6MjA1NTQyNzQ0OH0.xfjAzCp8wpLuGQKeqXKWCfm4mdqtHnaSrhNREE_6obY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);